baseURL: https://selgamal.github.io
languageCode: en-us
title: Sherif ElGamal
theme: toha

markup:
  goldmark:
    renderer:
      unsafe: true

# enableBlogPost: true

taxonomies:
  category: categories
  series: series
  author: authors
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON

copyright: © Sherif ElGamal Copyright.

features:
  # Enable and configure portfolio
  portfolio:
    enable: true
  # Enable and configure blog posts
  blog:
    enable: true
    # Share post on different social media
    shareButtons:
      facebook: true
      twitter: true
      linkedin: true
      reddit: true
      whatsapp: true
      email: true

Params:
  logo: 
    favicon: "/images/logo_only.svg"
  background: "/images/bg-f.jpg"
  topNavBar:
    maxVisibleSections: 10
  customCSS:
    - css/style.css
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
      # show custom menus in the footer
      customMenus: false
    # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: true
    # Show/hide credentials section in the footer. Default is "true".
    credentials:
      enable: true

    # Show/hide newsletter section in the footer. Default is "true".
    # Currently, it supports "mailchimp".
    newsletter:
      enable: false

    # Show/hide disclaimer notice in the footer. Default is "false".
    disclaimer:
      enable: false